# Generated by Django 4.2.6 on 2024-09-08 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company'),
        ('job', '0003_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
    ]
