# Generated by Django 4.2.6 on 2024-09-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
