# Generated by Django 4.1.7 on 2024-09-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
