# Generated by Django 4.1.7 on 2024-09-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.CharField(default='correo@gmail.com', max_length=100),
        ),
    ]
